## === for top level =================
#TOPDIR=./..

#EXCLUDE_DIRS= include builds
#LIBPATH=$(TOPDIR)/builds/lib
#BINPATH=$(TOPDIR)/builds/bin

#include $(TOPDIR)/Makefile.env


## === for top module =================
#TOPDIR=./../..

#TARGET=main

#LIBPATH=$(TOPDIR)/builds/lib
#BINPATH=$(TOPDIR)/builds/bin

#CFLAGS= -I$(TOPDIR)/include/xx
#LDFLAGS= -lxx

#include $(TOPDIR)/Makefile.env



## === for sub module =================
TOPDIR=./../..

LIB=jz2440_mem.a
LIBPATH=$(TOPDIR)/builds/lib

INCPATH=$(TOPDIR)/include/
CFLAGS= -I$(INCPATH)

include $(TOPDIR)/Makefile.env


